version: "3.9"
services:
  meilisearch:
    image: getmeili/meilisearch:v0.22.0
    restart: always
    ports:
      - 7700:7700
    environment: 
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: 1
    volumes:
      - ./meilisearch/data:/data.ms